End-to-End Build Workflow
aws/amazon-cloudwatch-agent pull request #1416
Opened 2024-11-08 19:49 UTC by okankoAMZ

# Description of the issue
Allows us to build and test with operator for full end-to-end testing

# Description of changes
Added new workflow to build agent and operator together

# License
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

# Tests
[![Build Test Artifacts](https://github.com/aws/amazon-cloudwatch-agent/actions/workflows/build-test-artifacts.yml/badge.svg)](https://github.com/aws/amazon-cloudwatch-agent/actions/workflows/build-test-artifacts.yml)
https://github.com/aws/amazon-cloudwatch-agent/actions/runs/11748578760
Example of workflow call working as intended for BuildArtifacts: https://github.com/aws/amazon-cloudwatch-agent/actions/runs/12321954899

# Requirements
_Before commit the code, please do the following steps._
1. Run `make fmt` and `make fmt-sh`
2. Run `make lint`

2024-11-08 21:01 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +
nit:
```suggestion
```

2024-11-08 21:01 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +            group: ${{ github.workflow }}-operator-${{ inputs.operator-branch}}
nit:
```suggestion
            group: ${{ github.workflow }}-operator-${{ inputs.operator-branch }}
```

2024-11-08 21:01 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +            repository:  ${{needs.GetLatestOperatorCommitSHA.outputs.operator_repo_name}}
nit:
```suggestion
            tag: ${{ needs.GetLatestOperatorCommitSHA.outputs.operator_commit_sha }}
            target-branch: ${{ needs.GetLatestOperatorCommitSHA.outputs.operator_commit_sha }}
            repository:  ${{ needs.GetLatestOperatorCommitSHA.outputs.operator_repo_name }}
```

2024-11-08 21:01 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +            group: "Build-Test-Artifacts-${{github.ref_name}}"
nit:
```suggestion
            group: "Build-Test-Artifacts-${{ github.ref_name }}"
```

2024-11-08 21:02 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +
nit:
```suggestion
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT
```

2024-11-08 21:03 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +                ref: ${{inputs.operator-branch}}
nit:
```suggestion
            operator_commit_sha: ${{ steps.get_latest_sha.outputs.operator_sha }}
            operator_repo_name: ${{ env.OPERATOR_GITHUB_REPO_NAME }} 
        steps:
          - name: Checkout the target repo
            uses: actions/checkout@v3
            with:
                repository: ${{ env.OPERATOR_GITHUB_REPO_NAME }} 
                ref: ${{ inputs.operator-branch }}    

```

2024-11-08 21:04 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +    ECR_OPERATOR_RELEASE_IMAGE: ${{ vars.ECR_TARGET_ALLOCATOR_TEST_OPERATOR_REPO}}
nit:
```suggestion
    ECR_TARGET_ALLOCATOR_STAGING_REPO: ${{ vars.ECR_TARGET_ALLOCATOR_STAGING_REPO }}
    ECR_OPERATOR_RELEASE_IMAGE: ${{ vars.ECR_TARGET_ALLOCATOR_TEST_OPERATOR_REPO }}
```

2024-11-08 21:04 UTC, musa-asad submitted a review, later dismissed

2024-12-01 04:53 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +                required: true
If we have a default, does it need to be required?

2024-12-01 08:21 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +    ECR_OPERATOR_RELEASE_IMAGE: ${{ vars.ECR_TARGET_ALLOCATOR_TEST_OPERATOR_REPO}}
These aren't being used?

2024-12-01 18:56 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +            target-branch: ${{needs.GetLatestOperatorCommitSHA.outputs.operator_commit_sha}}
```suggestion
            target-sha: ${{needs.GetLatestOperatorCommitSHA.outputs.operator_commit_sha}}
```

2024-12-01 19:10 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +            cancel-in-progress: true
Do we need this concurrency? The workflow it calls already has one.

2024-12-13 18:42 UTC, musa-asad commented on .github/workflows/build-test-artifacts.yml
> +        type: boolean
```suggestion
  workflow_dispatch:
    inputs:
      test-image-before-upload:
        description: "Run Test on the new container image"
        default: true
        type: boolean
  workflow_call:
    inputs:
      test-image-before-upload:
        description: "Run Test on the new container image"
        default: true
        type: boolean
```

2024-12-13 18:47 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +    ECR_OPERATOR_RELEASE_IMAGE: ${{ vars.ECR_TARGET_ALLOCATOR_TEST_OPERATOR_REPO}}
```suggestion
    OPERATOR_GITHUB_REPO_NAME: "aws/amazon-cloudwatch-agent-operator"
```

2024-12-13 18:50 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +                required: true
```suggestion
                required: false
```

2024-12-13 18:50 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +                default: 'main'
```suggestion
on:
    workflow_dispatch:
        inputs:
            operator-branch:
                required: false
                type: string
                default: 'main'
    workflow_call:
        inputs:
            operator-branch:
                required: false
                type: string
                default: 'main'
```

2024-12-13 18:53 UTC, musa-asad commented on .github/workflows/e2e-build.yml
> +        uses: aws/amazon-cloudwatch-agent-operator/.github/workflows/build-and-upload.yml@e2e-testing
```suggestion
        uses: aws/amazon-cloudwatch-agent-operator/.github/workflows/build-and-upload.yml@main
```

2024-12-13 18:54 UTC, musa-asad requested changes
Please make these minor changes, otherwise it's good to go!

2024-12-13 19:33 UTC, musa-asad commented on .github/workflows/build-test-artifacts.yml
> +    if: ${{inputs.test-image-before-upload || true }}
```suggestion
    if: ${{true || inputs.test-image-before-upload }}
```

2024-12-13 19:33 UTC, musa-asad commented on .github/workflows/build-test-artifacts.yml
> +    if: ${{ contains(github.ref_name, 'main')  && (inputs.test-image-before-upload || true) }}
```suggestion
    if: ${{ contains(github.ref_name, 'main')  && (true || inputs.test-image-before-upload) }}
```

2024-12-13 19:38 UTC, musa-asad commented on .github/workflows/build-test-artifacts.yml
> +    if: ${{inputs.test-image-before-upload == null || inputs.test-image-before-upload}}
```suggestion
    if: ${{ (github.event_name != 'workflow_call') || inputs.test-image-before-upload }}
```

2024-12-13 19:38 UTC, musa-asad commented on .github/workflows/build-test-artifacts.yml
> +    if: ${{ contains(github.ref_name, 'main')  && (inputs.test-image-before-upload == null ||inputs.test-image-before-upload) }}
```suggestion
    if: ${{ contains(github.ref_name, 'main') && ((github.event_name != 'workflow_call') || inputs.test-image-before-upload) }}
```

2024-12-13 20:34 UTC, varunch77 approved these changes

2024-12-13 20:48 UTC, TravisStark approved these changes

2024-12-13 21:00 UTC, merged